on:
  pull_request:
    types: [labeled, opened, reopened, synchronize]

jobs:
  run-precommit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get latest push changes
      id: changed-files
      uses: tj-actions/changed-files@v44
      with:
        since_last_remote_commit: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Pre-commit
      run: pip install pre-commit

    - name: Run pre-commit on changed files
      run: |
        if [ -n "${{ steps.changed-files.outputs.all_changed_files }}" ]; then
          pre-commit run --files ${{ steps.changed-files.outputs.all_changed_files }}
        else
          echo "No files have changed, skipping pre-commit."
        fi
